---
#Install apt-transport-https to add docker repository
- name: Make sure apt-transport-https is installed
  apt:
    pkg: apt-transport-https
    state: installed

#Install ca-certificates to add docker repository
- name: Make sure ca-certificates is installed
  apt: 
    pkg: ca-certificates
    state: installed

#Add docker repository and run a apt-get update
- name: Add Docker repository and update apt cache
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo debian-jessie main'
    update_cache: yes
    state: present

#Add docker repository key
- name: Add Docker repository key
  apt_key:
    id: "58118E89F3A912897C070ADBF76221572C52609D"
#   keyserver: "hkp://p80.pool.sks-keyservers.net:80"
    url: "https://apt.dockerproject.org/gpg"
    state: present
  register: add_repository_key

- name: Alternative | Add Docker repository key
  shell: "curl -sSL {{ apt_key_url }} | sudo apt-key add -"
  when: add_repository_key|failed

#Install docker package
- name: Install docker package
  apt:
    pkg: docker-engine
    state: latest
